### PR TITLE
Added composer file with leafo/scssphp as dependence

### PR DESCRIPTION
**Pull request by JumpLink**
My scss files was not compile without this, see screenshot.
This pull request fix this for me.

auswahl_074

### CODE REVIEW

**Comment by christianWilling** [comment]
the point is that `leafo/scssphp` is an `require-dev` from `kriswallsmith/assetic` and thats an `require` from `october/rain` but there is an issule with the same error https://github.com/christianWilling/Scss/issues/6
so have you an idear why the package is not there ?

**Comment by JumpLink** [comment]
Mhh because it needs to be a `require` instead of a `require-dev`?
Just a guess: `require-dev` are not installed by default. It be only installed when you expizit install developer dependencies.

Unless this is handled in composer like in bower, I do not know that.

**Comment by christianWilling** [comment]
oh yes i'm sry of curse your right.
but the scss compile will be in the octobercms core so i will fix it there. if this is ok for you

**Comment by JumpLink** [comment]
Of course

**Comment by McSuckelaer** [comment]
So, ummm. Forgive my noobyness but what do i have to do to get Scss working again? I changed the composer.json file like described above but no result.

**Comment by JumpLink** [comment]
@McSuckelaer you need to run `composer install` in the root of the plugin if you have the composer file added.
See [composer basic usage](https://getcomposer.org/doc/01-basic-usage.md) for more information.

**Comment by christianWilling** [comment]
or you can require leafo/scssphp in the main composer.json of octobercms

**Comment by JumpLink** [comment]
@christianWilling this was the first I have tried but with problems

**Comment by McSuckelaer** [comment]
@Jumplink @christianWilling Awesome, i forgot. Got it working again. :)

**Comment by christianWilling** [comment]
oh ok but its good that you can work now untile the pr in octobercms is done

**Comment by McSuckelaer** [comment]
Thanks for the great support guys. Simply can't go without the SCSS plugin. :page_facing_up:

**Comment by JumpLink** [comment]
@christianWilling Good luck and thank you for your work on October!

**Comment by christianWilling** [comment]
@JumpLink no problem i think my next plugin will be an easy drag-n-drop sidebuilder based on the staticpages plugin where you can define particals with some options and for every partical.

but thats is until now only in planing in my head. But i will start developing this in the next weeks

**Comment by JumpLink** [comment]
Very nice to hear, we are [also working on some nice plugins](https://github.com/JumpLinkNetwork). :)

**Comment by McSuckelaer** [comment]
October just keeps getting better cause of awesome work from guys like you! One of these days i will learn more and try to make plugins of my own. :)

**Comment by christianWilling** [comment]
@JumpLink you plugins lock also nice:)
@McSuckelaer thanks for the nice feedback that's the reason to develop plugins and make them public

**Pull request closed without merging**
